"""add topic summaries and article titles

Revision ID: 6cbed30c76d3
Revises: 
Create Date: 2026-05-17 02:24:34.596724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbed30c76d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ko_summary', sa.Text(), nullable=True),
    sa.Column('ja_summary', sa.Text(), nullable=True),
    sa.Column('ko_neutral_title', sa.String(length=512), nullable=True),
    sa.Column('ja_neutral_title', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('press_name', sa.String(length=255), nullable=False),
    sa.Column('nation', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('ko_title', sa.String(length=512), nullable=True),
    sa.Column('ja_title', sa.String(length=512), nullable=True),
    sa.Column('ko_text', sa.Text(), nullable=True),
    sa.Column('ja_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index('idx_article_topic_id', 'article', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_article_topic_id', table_name='article')
    op.drop_table('article')
    op.drop_table('topic')
    # ### end Alembic commands ###
